# Site settings
author: Travis Lawson
title: The variables to my methods
header-img: img/home-bg.png
email: travislawclimb@gmail.com
copyright_name: Travis Lawson
description: > # this means to ignore newlines until "baseurl:"
  Coding and everything in between
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Tlaw92

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
